
- name: Install Pre-requisites of Grafana for Ubuntu
  apt:
    name:
      - software-properties-common
      - apt-transport-https
      - ca-certificates
      - curl
  tags: [prerequisites]
  when: ansible_distribution == "Ubuntu"

- name: Import Grafana Repository Key for Ubuntu
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present
  tags: [prerequisites]
  when: ansible_distribution == "Ubuntu"

- name: Import Grafana Installation Repository for Ubuntu
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Install Grafana for Ubuntu
  apt:
    name: grafana
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Enable Grafana Service for Ubuntu
  systemd:
    name: grafana-server
    state: started
    enabled: yes
  when: ansible_distribution == "Ubuntu"

- name: Checking SELinux Status for CentOS
  command: getenforce
  register: selinux_status
  when: ansible_distribution == "CentOS"

- name: Disable SELinux only when Enabled for CentOS
  when: selinux_status.stdout == "Enforcing"
  command: setenforce 0
  when: ansible_distribution == "CentOS"

- name: Configure SELinux for CentOS
  lineinfile:
    path: /etc/sysconfig/selinux
    regexp: '^SELINUX='
    line: 'SELINUX=disabled'
  when: selinux_status.stdout == "Enforcing"
  when: ansible_distribution == "CentOS"

- name: Reboot Managed Node when SELinux is Disabled for CentOS
  command: ls
  async: 0
  poll: 0
  when: selinux_status.stdout == "Enforcing"
  when: ansible_distribution == "CentOS"

- name: Create Grafana Repository File for CentOS
  template:
    src: Grafana_Repository.j2
    dest: /etc/yum.repos.d/grafana.repo
  when: ansible_distribution == "CentOS"

- name: Install Grafana for CentOS
  yum:
    name: grafana
    state: present
    use_backend: dnf4
  when: ansible_distribution == "CentOS"

- name: Enable Grafana Service for CentOS
  systemd:
    name: grafana-server
    state: started
    enabled: yes
  when: ansible_distribution == "CentOS"

