
- name: Install Nagios for Ubuntu
  apt:
    name:
      - nagios4-core
      - nagios-plugins
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: Install Nagios on CentOS
  yum:
    name:
      - nagios
      - nagios-plugins
    state: latest
  when: ansible_distribution == "CentOS"
